.github/workflows/package.yml
----
:books: Documentation preview :books:: https://serious-scaffold-python--2.org.readthedocs.build/en/2/
=> Fix PyPI package upload.

.github/FUNDING.yml
Signed-off-by: Xuan (Sean) Hu <i@huxuan.org>
----
:books: Documentation preview :books:: https://serious-scaffold-python--4.org.readthedocs.build/en/4/
=> Add sponsors badge.

.github/workflows/lint-test.yml, .github/workflows/readthedocs-preview.yml, README.md, pyproject.toml
----
:books: Documentation preview :books:: https://serious-scaffold-python--5.org.readthedocs.build/en/5/
=> Minor changes mostly for badge.

README.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--6.org.readthedocs.build/en/6/
=> Add hyperlinks for badges.

README.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--8.org.readthedocs.build/en/8/
=> Refine README.

.github/workflows/ci.yml, README.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--9.org.readthedocs.build/en/9/
=> Rename lint-test.yml to ci.yml with badges refined.

.pre-commit-config.yaml, .vscode/settings.json, Makefile, README.md, constraints/default.txt, requirements/lint.txt
----
:books: Documentation preview :books:: https://serious-scaffold-python--10.org.readthedocs.build/en/10/
=> Add isort in pre-commit and CI (with Makefile).

.github/workflows/ci.yml
----
:books: Documentation preview :books:: https://serious-scaffold-python--14.org.readthedocs.build/en/14/
=> Run CI for pull request synchronize event only.

.github/workflows/ci.yml
----
:books: Documentation preview :books:: https://serious-scaffold-python--15.org.readthedocs.build/en/15/
=> Run CI for main branch push.

.vscode/settings.json, Makefile.jinja, copier.yaml
----
:books: Documentation preview :books:: https://serious-scaffold-python--24.org.readthedocs.build/en/24/
=> Compatible with yaml-sort extension v6.5.0.

pyproject.toml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--32.org.readthedocs.build/en/32/
=> Update template accordingly.

.gitlab-ci.yml, .gitlab-ci.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--42.org.readthedocs.build/en/42/
=> Support test coverage in gitlab ci.

.github/FUNDING.yml.jinja, README.md, README.md.jinja, copier.yaml, docs/conf.py, docs/conf.py.jinja, pyproject.toml
----
:books: Documentation preview :books:: https://serious-scaffold-python--46.org.readthedocs.build/en/46/
=> Change repo namespace in various places.

README.md, README.md.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--62.org.readthedocs.build/en/62/
=> Add badge for ruff.

.github/workflows/release.yml, .gitlab-ci.yml, .gitlab-ci.yml.jinja, Makefile, Makefile.jinja
Fix gitlab pages.
----
:books: Documentation preview :books:: https://serious-scaffold-python--73.org.readthedocs.build/en/73/
=> More elegant public dir.

.github/workflows/release.yml, .gitlab-ci.yml, .gitlab-ci.yml.jinja, .readthedocs.yaml, .vscode/settings.json, Makefile, Makefile.jinja, constraints/default.txt, pyproject.toml, pyproject.toml.jinja, requirements/docs.txt, requirements/tests.txt
----
:books: Documentation preview :books:: https://serious-scaffold-python--74.org.readthedocs.build/en/74/
=> Use native readthedocs build instead.

.github/workflows/ci.yml, .github/workflows/ci.yml.jinja, .github/workflows/release.yml, .gitlab-ci.yml, .gitlab-ci.yml.jinja, .pre-commit-config.yaml, Makefile, Makefile.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--88.org.readthedocs.build/en/88/
=> Refine Makefile.

README.md, template/README.md.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--104.org.readthedocs.build/en/104/
=> docs: Add pre-commit badge.

.github/workflows/package.yml, .github/workflows/pages.yml, .gitlab-ci.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/package.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/pages.yml.jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab-ci.yml[% endif %].jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--112.org.readthedocs.build/en/112/
=> chore: Fix package ci with shorter badge names.

scripts/generate-coverage-badge.sh, template/scripts/generate-coverage-badge.sh
----
:books: Documentation preview :books:: https://serious-scaffold-python--114.org.readthedocs.build/en/114/
=> chore: Align coverage badge colors with GitLab.

.github/dependabot.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/dependabot.yml
----
:books: Documentation preview :books:: https://serious-scaffold-python--116.org.readthedocs.build/en/116/
=> ci: Integrate with Dependabot version updates.

docs/index.md, template/docs/index.md.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--132.org.readthedocs.build/en/132/
=> docs: Add emoji for indices.

.github/workflows/package.yml, .github/workflows/pages.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/package.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/pages.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--135.org.readthedocs.build/en/135/
=> build: Fix bug due to new version of checkout action.

.github/workflows/package.yml, .github/workflows/pages.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/package.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/pages.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--136.org.readthedocs.build/en/136/
=> ci: Fix error in GitHub Actions.

.github/workflows/package.yml, .github/workflows/pages.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/package.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/pages.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--137.org.readthedocs.build/en/137/
=> ci: Fix GitHub Actions due to new version of checkout.

.github/workflows/package.yml, .github/workflows/pages.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/package.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/pages.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--143.org.readthedocs.build/en/143/
=> ci: Revert GitHub Action changes: no fetch tags for checkout.

.github/workflows/ci.yml, .github/workflows/pages.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/pages.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--145.org.readthedocs.build/en/145/
=> ci: Fetch tags for GitHub Pages generation.

.readthedocs.yaml, .vscode/settings.json, template/.readthedocs.yaml.jinja, template/.vscode/settings.json
----
:books: Documentation preview :books:: https://serious-scaffold-python--148.org.readthedocs.build/en/148/
=> ci: Unshallow git clone on readthedocs.

docs/index.md, template/docs/index.md.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--150.org.readthedocs.build/en/150/
=> docs: Add self to toctree.

.github/workflows/ci.yml, .github/workflows/pages.yml, .gitlab-ci.yml, .readthedocs.yaml, Makefile, template/.readthedocs.yaml.jinja, template/Makefile.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/pages.yml.jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab-ci.yml[% endif %].jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--151.org.readthedocs.build/en/151/
=> chore: Download existing changelog if exists for incremental generation.

Makefile, template/Makefile.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--152.org.readthedocs.build/en/152/
=> chore: Unify variable expansion with minor refinement in Makefile.

.gitlab-ci.yml, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab-ci.yml[% endif %].jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--153.org.readthedocs.build/en/153/
=> ci: Fix coverage report for GitLab CI/CD with stage name refined.

.github/workflows/ci.yml, .github/workflows/lint-pull-request-title.yml, .github/workflows/pages.yml, .github/workflows/readthedocs-preview.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/lint-pull-request-title.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/pages.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/readthedocs-preview.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--160.org.readthedocs.build/en/160/
=> ci: Refine workflows for GitHub Actions.

.github/workflows/release.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--164.org.readthedocs.build/en/164/
=> ci: Fix release workflow for GitHub Actions.

.github/workflows/release.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--166.org.readthedocs.build/en/166/
=> ci: Fix file already exists error for download artifact.

.github/workflows/ci.yml, .github/workflows/release.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--167.org.readthedocs.build/en/167/
=> ci: Fix release notes problem.

Makefile, template/Makefile.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--172.org.readthedocs.build/en/172/
=> ci: Fix GitLab CI/CD pipeline.

.github/workflows/ci.yml, .gitignore, Makefile, template/.gitignore.jinja, template/Makefile.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--173.org.readthedocs.build/en/173/
=> chore: Workflow refinement and more generated files handled.

.github/workflows/release.yml, .gitlab-ci.yml, .vscode/settings.json, copier.yaml, template/.vscode/settings.json, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab-ci.yml[% endif %].jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--175.org.readthedocs.build/en/175/
=> chore: Remove unnecessary yaml sort keywords.

.github/workflows/ci.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--189.org.readthedocs.build/en/189/
=> ci: Only run dependabot job for Python update.

README.md, docs/_static/badges/logo.json, includes/variable.jinja, template/README.md.jinja, template/docs/_static/badges/[% if project_name == "Serious Scaffold Python" %]logo.json[% endif %].jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--191.org.readthedocs.build/en/191/
=> docs: Make logo badge as endpoint badge.

Makefile, README.md, includes/variable.jinja, scripts/generate-coverage-badge.sh, template/Makefile.jinja, template/scripts/generate-coverage-badge.sh
----
:books: Documentation preview :books:: https://serious-scaffold-python--192.org.readthedocs.build/en/192/
=> docs: Move coverage badge json to `_static/badges`.

.github/workflows/ci.yml, .github/workflows/pr.yml, .gitlab/ci/mr.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/pr.yml, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/ci/mr.yml
----
:books: Documentation preview :books:: https://serious-scaffold-python--197.org.readthedocs.build/en/197/
=> ci: Use single quotes for grep and echo with literal string.

.pre-commit-config.yaml, template/.pre-commit-config.yaml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--196.org.readthedocs.build/en/196/
=> chore: Add args to 'check-merge-conflict' in pre-commit.

.github/workflows/release.yml, .gitlab/ci/ci.yml, .gitlab/ci/release.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/ci/ci.yml.jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/ci/release.yml
----
:books: Documentation preview :books:: https://serious-scaffold-python--199.org.readthedocs.build/en/199/
=> ci: Support prerelease according to PEP440.

.gitignore, template/.gitignore.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--206.org.readthedocs.build/en/206/
=> chore: Remove docs/changelog.md from .gitignore.

.vscode/settings.json, constraints/3.10.txt, constraints/3.11.txt, constraints/3.12.txt, constraints/3.8.txt, constraints/3.9.txt, docs/conf.py, docs/dev/env.md, docs/dev/index.md, docs/index.md, requirements/docs.txt, template/.vscode/settings.json, template/constraints/3.10.txt, template/constraints/3.11.txt, template/constraints/3.12.txt, template/constraints/3.8.txt, template/constraints/3.9.txt, template/docs/conf.py.jinja, template/docs/dev/env.md, template/docs/dev/index.md, template/docs/index.md.jinja, template/requirements/docs.txt
----
:books: Documentation preview :books:: https://serious-scaffold-python--209.org.readthedocs.build/en/209/
=> docs: Add documentation for environment management.

docs/dev/env.md, template/docs/dev/env.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--210.org.readthedocs.build/en/210/
=> docs: Fix capitalization consistency problem.

docs/dev/env.md, template/docs/dev/env.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--211.org.readthedocs.build/en/211/
=> docs: Further utilize note admonition.

scripts/generate-coverage-badge.sh, template/scripts/generate-coverage-badge.sh
----
:books: Documentation preview :books:: https://serious-scaffold-python--215.org.readthedocs.build/en/215/
=> chore: More robust coverage badge generation.

docs/dev/env.md, template/docs/dev/env.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--216.org.readthedocs.build/en/216/
=> docs: Unify title capitalization for environment management.

docs/dev/index.md, docs/dev/proj.md, template/docs/dev/index.md, template/docs/dev/proj.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--217.org.readthedocs.build/en/217/
=> docs: Add docs for project management.

docs/dev/proj.md, template/docs/dev/proj.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--218.org.readthedocs.build/en/218/
=> docs: Refine project management docs.

.vscode/settings.json, README.md, copier.yaml, docs/conf.py, pyproject.toml, template/.vscode/settings.json, template/README.md.jinja, template/docs/conf.py.jinja, template/pyproject.toml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--219.org.readthedocs.build/en/219/
=> docs: Add development status as template option.

.vscode/settings.json, docs/conf.py, docs/dev/commit.md, docs/dev/index.md, template/.vscode/settings.json, template/docs/conf.py.jinja, template/docs/dev/commit.md, template/docs/dev/index.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--222.org.readthedocs.build/en/222/
=> docs: Add docs for commit convention.

docs/dev/index.md, docs/dev/release.md, template/docs/dev/index.md, template/docs/dev/release.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--224.org.readthedocs.build/en/224/
=> docs: Add docs for release process.

.vscode/settings.json, docs/dev/index.md, template/.vscode/settings.json, template/docs/dev/index.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--225.org.readthedocs.build/en/225/
=> docs: Fulfill the index of the development section.

README.md, copier.yaml, pyproject.toml, template/pyproject.toml.jinja
----
:books: Documentation preview :books:: https://serious-scaffold-python--227.org.readthedocs.build/en/227/
=> docs: Change the project description and keywords.

docs/dev/proj.md, template/docs/dev/proj.md
----
:books: Documentation preview :books:: https://serious-scaffold-python--231.org.readthedocs.build/en/231/
=> docs: Refine project configuration related part.

.gitignore, template/.gitignore.jinja
Sync gitignore with https://github.com/github/gitignore/blob/main/Python.gitignore
Close #234 
----
:books: Documentation preview :books:: https://ss-python--241.org.readthedocs.build/en/241/
=> chore: Update gitignore.

.pre-commit-config.yaml, .vscode/extensions.json, .vscode/settings.json, Makefile, README.md, docs/conf.py, pyproject.toml, requirements/lint.txt, src/ss_python/settings.py, template/.pre-commit-config.yaml.jinja, template/.vscode/extensions.json, template/.vscode/settings.json, template/Makefile.jinja, template/README.md.jinja, template/docs/conf.py.jinja, template/pyproject.toml.jinja, template/requirements/lint.txt, template/src/{{ module_name }}/settings.py.jinja
----
:books: Documentation preview :books:: https://ss-python--246.org.readthedocs.build/en/246/
=> chore: Sync ruff.

.gitignore, Makefile, template/.gitignore.jinja, template/Makefile.jinja
Reference: https://github.com/pdm-project/pdm/blob/main/src/pdm/cli/templates/default/.gitignore#L112
----
📚 Documentation preview 📚: https://ss-python--261.org.readthedocs.build/en/261/
=> chore: Include .pdm-build/ in gitignore and make clean.

LICENSE
Fix the CI error: https://github.com/serious-scaffold/ss-python/actions/runs/7468979734/job/20325353464
----
📚 Documentation preview 📚: https://ss-python--266.org.readthedocs.build/en/266/
=> chore: Update the date in LICENSE.

.gitlab/ci/ci.yml, .gitlab/ci/devcontainer.yml, .gitlab/ci/mr.yml, .gitlab/ci/release.yml, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/ci/ci.yml.jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/ci/devcontainer.yml, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/ci/mr.yml, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/ci/release.yml
----
📚 Documentation preview 📚: https://ss-python--269.org.readthedocs.build/en/269/
=> chore: Use `rules` instead of `only` in GitLab CI/CD.

.devcontainer/prebuild/.devcontainer/Dockerfile, .devcontainer/prebuild/.devcontainer/devcontainer.json, template/.devcontainer/prebuild/.devcontainer/Dockerfile.jinja, template/.devcontainer/prebuild/.devcontainer/devcontainer.json
----
📚 Documentation preview 📚: https://ss-python--267.org.readthedocs.build/en/267/
=> chore: Add non-root user and install pre-commit in the image.

README.md, includes/variable.jinja, template/README.md.jinja
Please refer to https://github.com/huxuan/ss-python/blob/xuan.hu/devcontainers-badge/README.md for actual effect.
----
📚 Documentation preview 📚: https://ss-python--282.org.readthedocs.build/en/282/
=> docs: Add devcontainer related badges in README.

.github/workflows/devcontainer.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/devcontainer.yml.jinja
----
📚 Documentation preview 📚: https://ss-python--286.org.readthedocs.build/en/286/
=> chore: Support manually trigger for GitHub devcontainer workflow.

pyproject.toml, template/pyproject.toml.jinja
Reference:
- https://pdm-project.org/latest/dev/changelog/#release-v2120-2024-01-17
- https://github.com/pdm-project/pdm/pull/2564
----
📚 Documentation preview 📚: https://ss-python--288.org.readthedocs.build/en/288/
=> chore: Rename config `package-type` to `distribution` for pdm v2.12.0.

.vscode/settings.json, template/.vscode/settings.json
Reference:  https://stackoverflow.com/a/77637765
----
📚 Documentation preview 📚: https://ss-python--289.org.readthedocs.build/en/289/
=> chore: Update settings for code actions on save for vscode v1.85.0.

.gitlab-ci.yml, .gitlab/ci/ci.yml, .gitlab/ci/release.yml, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab-ci.yml[% endif %].jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/ci/ci.yml.jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/ci/release.yml
----
📚 Documentation preview 📚: https://ss-python--283.org.readthedocs.build/en/283/
=> ci: Utilize `before_script` in GitLab CI/CD.

.vscode/settings.json, copier.yaml, template/.devcontainer/devcontainer.json.jinja, template/.devcontainer/prebuild/.devcontainer/devcontainer.json.jinja, template/.vscode/settings.json
----
📚 Documentation preview 📚: https://ss-python--290.org.readthedocs.build/en/290/
=> chore: Adaptive container registry host.

.github/workflows/release.yml, .readthedocs.yaml, template/.readthedocs.yaml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja
----
📚 Documentation preview 📚: https://ss-python--299.org.readthedocs.build/en/299/
=> ci: Dynamic CI_PAGES_URL when building GitHub Pages and ReadTheDocs.

README.md, template/README.md.jinja
Reference: https://github.com/conventional-commits/conventionalcommits.org/tree/master?tab=readme-ov-file#badges
----
📚 Documentation preview 📚: https://ss-python--307.org.readthedocs.build/en/307/
=> doc: Add badge for conventional commits.

README.md, includes/variable.jinja
----
📚 Documentation preview 📚: https://ss-python--312.org.readthedocs.build/en/312/
=> docs: add commitlint badge in README

.github/workflows/release.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja
----
📚 Documentation preview 📚: https://ss-python--320.org.readthedocs.build/en/320/
=> ci: simplify expression in GitHub Actions

.dockerignore, template/.dockerignore
Test according to https://stackoverflow.com/a/40966234
----
📚 Documentation preview 📚: https://ss-python--323.org.readthedocs.build/en/323/
=> chore: add .dockerignore to reduce context size

.github/workflows/ci.yml, .github/workflows/commitlint.yml, .github/workflows/devcontainer.yml, .github/workflows/readthedocs-preview.yml, .github/workflows/release.yml, .github/workflows/renovate.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/commitlint.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/devcontainer.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/readthedocs-preview.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/renovate.yml.jinja
----
📚 Documentation preview 📚: https://ss-python--336.org.readthedocs.build/en/336/
=> chore: specify the versions of GitHub Actions

.github/workflows/release.yml, .gitlab/workflows/release.yml, .readthedocs.yaml, template/.readthedocs.yaml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/release.yml.jinja
----
📚 Documentation preview 📚: https://ss-python--342.org.readthedocs.build/en/342/
=> ci: apply PDM_NO_EDITABLE for docs release

.pre-commit-config.yaml, template/.pre-commit-config.yaml.jinja
----
📚 Documentation preview 📚: https://ss-python--344.org.readthedocs.build/en/344/
=> chore: add renovate config validator pre-commit hoook

README.md, includes/variable.jinja
----
📚 Documentation preview 📚: https://ss-python--348.org.readthedocs.build/en/348/
=> chore: add Renovate status badge and sort alphabetically

.github/workflows/renovate.yml, .gitlab/workflows/renovate.yml, .renovaterc.json, template/.renovaterc.json.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/renovate.yml.jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/renovate.yml
- Dependency Dashboard: https://gitlab.com/serious-scaffold/ss-python-gitlab/-/issues/1
- Job: https://gitlab.com/serious-scaffold/ss-python-gitlab/-/jobs/6295590732
- Merge request: https://gitlab.com/serious-scaffold/ss-python-gitlab/-/merge_requests/1
P.S. Both `github-release` and `github-tags` needs extra configuration of GITHUB_TOKEN on GitLab, so `git-tags` is the best solution I found. But it seems that, the pr title can not be customized specifically. Any suggestions are welcome.
----
📚 Documentation preview 📚: https://ss-python--358.org.readthedocs.build/en/358/
=> chore: update template with renovate

docs/dev/proj.md, template/docs/dev/proj.md.jinja
----
📚 Documentation preview 📚: https://ss-python--379.org.readthedocs.build/en/379/
=> docs: optionally set GITHUB_COM_TOKEN for Renovate on GitLab

README.md, template/README.md.jinja
----
📚 Documentation preview 📚: https://ss-python--380.org.readthedocs.build/en/380/
=> docs: refine Features in README

.github/workflows/ci.yml, .gitlab/workflows/ci.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja
Corresponding GitLab merge request: https://gitlab.com/huxuan8528/ss-python/-/merge_requests/32
=> ci: unify consistency check in GitHub Action and GitLab CI

.github/workflows/renovate.yml, .renovaterc.json, template/.renovaterc.json.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/renovate.yml.jinja
Anyway, unified management of dependencies is best practice.
Related #391 
Test on prs:
- https://github.com/msclock/ss-python/pull/2
- https://github.com/msclock/ss-python/pull/3
=> perf: configure renovate for pre-commit

.copier-data.yml, README.md, pyproject.toml
----
📚 Documentation preview 📚: https://ss-python--434.org.readthedocs.build/en/434/
=> docs: change project description

template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/renovate.yml.jinja
Current rendering for other project will be like this:
=> chore: fix template for renovate GitHub workflow

template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja
See https://gitlab.com/serious-scaffold/ss-python-gitlab/-/jobs/6466730782
=> fix: exclude consistency job on gitlab

.github/workflows/ci.yml, .github/workflows/release.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja
It is a hotfix and partial work for #442
=> ci: pin the version in pdm-project/setup-pdm action

.github/workflows/ci.yml, .gitlab/workflows/ci.yml, .renovaterc.json, README.md, docs/dev/dev-env.md, docs/dev/proj.md, includes/sample.jinja, template/.renovaterc.json.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja, template/docs/dev/dev-env.md, template/docs/dev/proj.md.jinja
----
📚 Documentation preview 📚: https://ss-python--456.org.readthedocs.build/en/456/
=> chore: update all pipx installation with renovate

.github/workflows/ci.yml, .github/workflows/commitlint.yml, .github/workflows/devcontainer.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/commitlint.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/devcontainer.yml.jinja
Reverts serious-scaffold/ss-python#481
=> revert: use $default-branch placeholder instead of hard-coded main

pyproject.toml, template/pyproject.toml.jinja
=> chore: update project links

src/ss_python/cli.py, template/src/{{ module_name }}/cli.py.jinja
=> chore: typer follow up on no_args_is_help

.github/workflows/readthedocs-preview.yml, .readthedocs.yaml, template/.readthedocs.yaml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/readthedocs-preview.yml.jinja
----
📚 Documentation preview 📚: https://ss-python--506.org.readthedocs.build/en/506/
=> chore: trigger readthedocs when Makefile changes

.github/workflows/delete-untagged-packages.yml, template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/delete-untagged-packages.yml.jinja
Fix #297 
Test job: https://github.com/huxuan/ss-python/actions/runs/8848594086/job/24298721416
=> chore: add workflow to delete untagged packages

.renovaterc.json, template/.renovaterc.json.jinja
According to the job log here: https://github.com/serious-scaffold/ss-python/actions/runs/8962798207/job/24612176132
The current value for `pdm-backend` is `==2.21` rather than `2.21`, same for the new value, so the update script need to be changed accordingly.
```
2024-05-06T01:37:45.3199309Z                {
2024-05-06T01:37:45.3200049Z                  "packageName": "pdm-backend",
2024-05-06T01:37:45.3200961Z                  "depName": "pdm-backend",
2024-05-06T01:37:45.3201765Z                  "datasource": "pypi",
2024-05-06T01:37:45.3202680Z                  "depType": "build-system.requires",
2024-05-06T01:37:45.3203555Z                  "currentValue": "==2.2.1",
2024-05-06T01:37:45.3204380Z                  "currentVersion": "2.2.1",
2024-05-06T01:37:45.3205405Z …
```
=> chore: template update with renovate

.github/workflows/ci.yml, package.json, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/ci.yml.jinja
Fix #554 
1. Failed run to reproduce the error: https://github.com/huxuan/ss-python/actions/runs/9130722026/job/25108275521
2. Successful run to fix the error: https://github.com/huxuan/ss-python/actions/runs/9130738012/job/25108325761
3. Release workflow triggered by semantic-release: https://github.com/huxuan/ss-python/actions/runs/9130744432
=> chore: fix semantic-release on GitHub protected tags

docs/development/git-workflow.md, docs/development/index.md, template/docs/development/git-workflow.md.jinja, template/docs/development/index.md
Fix #492 
----
📚 Documentation preview 📚: https://ss-python--558.org.readthedocs.build/en/558/
=> docs: add git-workflow

.gitignore, template/.gitignore.jinja
Update content from https://github.com/github/gitignore/blob/main/Python.gitignore
Remova a TODO
=> chore: update gitignore

.github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, .readthedocs.yaml, Makefile, README.md, docs/changelog.md, docs/development/commit.md, docs/index.md, docs/management/release.md, includes/variable.jinja, pdm.lock, pyproject.toml, template/.gitignore.jinja, template/.readthedocs.yaml.jinja, template/Makefile.jinja, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/release.yml.jinja, template/docs/changelog.md, template/docs/development/commit.md, template/docs/index.md.jinja, template/docs/management/release.md.jinja, template/pyproject.toml.jinja
Depends on #550 and #553
----
📚 Documentation preview 📚: https://ss-python--552.org.readthedocs.build/en/552/
=> chore: remove git-changelog related stuff

docs/management/release.md, docs/management/settings.md, template/docs/management/release.md.jinja, template/docs/management/settings.md.jinja
Better to merge this after #577 
----
📚 Documentation preview 📚: https://ss-python--576.org.readthedocs.build/en/576/
=> docs: update release documentation

.github/workflows/ci.yml, .github/workflows/devcontainer.yml, .github/workflows/readthedocs-preview.yml, .github/workflows/release.yml, .gitlab/workflows/release.yml, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/devcontainer.yml.jinja, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/readthedocs-preview.yml.jinja, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/release.yml.jinja, template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/release.yml.jinja
1. Add names to GitHub Actions
2. Push dev container after test prod container
----
📚 Documentation preview 📚: https://ss-python--595.org.readthedocs.build/en/595/
=> chore: add names to GitHub Actions

.devcontainer/Dockerfile, .devcontainer/Dockerfile.dockerignore, .github/workflows/ci.yml, .gitlab/workflows/ci.yml, .pre-commit-config.yaml, .renovaterc.json, Makefile, pdm.lock, pyproject.toml, template/.devcontainer/Dockerfile.dockerignore, template/.devcontainer/Dockerfile.jinja, template/.pre-commit-config.yaml.jinja, template/.renovaterc.json.jinja, template/Makefile.jinja, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja, template/pyproject.toml.jinja
----
📚 Documentation preview 📚: https://ss-python--630.org.readthedocs.build/en/630/
=> refactor(no-release): make ruff standalone

.releaserc.json, template/.releaserc.json.jinja
=> chore: disable release on refactor commits

README.md, template/README.md.jinja
----
📚 Documentation preview 📚: https://ss-python--634.org.readthedocs.build/en/634/
=> chore: add badge for copier and pdm

.pre-commit-config.yaml, template/.pre-commit-config.yaml.jinja
Reference: https://github.com/pdm-project/pdm/pull/2994
=> chore: run pdm sync in post-rewrite stage of pre-commit

.github/workflows/ci.yml, .gitlab/workflows/ci.yml, Makefile, pdm.lock, pyproject.toml, template/Makefile.jinja, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja, template/pyproject.toml.jinja
----
📚 Documentation preview 📚: https://ss-python--650.org.readthedocs.build/en/650/
=> chore: watch docs and template

.renovaterc.json, template/.renovaterc.json.jinja
=> fix: fix renovate config for .readthedocs.yaml

README.md, includes/copier-answers-sample.yml, includes/sample.jinja, pyproject.toml
Fix #759 
----
📚 Documentation preview 📚: https://ss-python--781.org.readthedocs.build/en/781/
=> docs: update the short and long description

.github/workflows/devcontainer.yml, .gitlab/workflows/devcontainer.yml, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/devcontainer.yml.jinja, template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/devcontainer.yml.jinja
=> fix: build dev container when mounted file changed

template/.renovaterc.json.jinja
=> fix: fix renovate template bug

copier.yaml, includes/sample.jinja, includes/variable.jinja, includes/version_compare.jinja, template/.gitignore.jinja, template/.pre-commit-config.yaml.jinja, template/.releaserc.json.jinja, template/.renovaterc.json.jinja, template/LICENSE.jinja, template/Makefile.jinja, template/README.md.jinja, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/ci.yml.jinja, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/devcontainer.yml.jinja, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/release.yml.jinja, template/[% if repo_platform == 'github' %].github[% endif %]/workflows/renovate.yml.jinja, template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja, template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/devcontainer.yml.jinja, template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/release.yml.jinja, template/docs/advanced/cicd.md.jinja, template/docs/conf.py.jinja, template/docs/development/git-workflow.md.jinja, template/docs/index.md.jinja, template/docs/management/init.md.jinja, template/pyproject.toml.jinja, template/src/{{ module_name }}/settings.py.jinja
=> refactor: use trim_blocks and lstrip_blocks to avoid unnecessary whitespace control

.renovaterc.json, template/.renovaterc.json.jinja
=> fix: update development lockfile with renovate

.readthedocs.yaml, template/.readthedocs.yaml.jinja
----
📚 Documentation preview 📚: https://ss-python--876.org.readthedocs.build/en/876/
=> fix: fix the readthedocs config

Makefile, template/Makefile.jinja
----
📚 Documentation preview 📚: https://ss-python--885.org.readthedocs.build/en/885/
=> feat(no-release): no default for dev lockfile
