serious-scaffold/ss-python

pyproject.toml

----
:books: Documentation preview :books:: https://serious-scaffold-python--3.org.readthedocs.build/en/3/

Fix meta error for license.

---

{{_copier_conf.answers_file}}.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--19.org.readthedocs.build/en/19/

No redundant newline at the end of coper answers file.

---

.github/FUNDING.yml
.github/FUNDING.yml.jinja
.github/workflows/ci.yml
.github/workflows/package.yml
.github/workflows/readthedocs-preview.yml
.github/workflows/readthedocs-preview.yml.jinja
.pre-commit-config.yaml
.readthedocs.yaml
.vscode/extensions.json
.vscode/settings.json
copier.yaml

----
:books: Documentation preview :books:: https://serious-scaffold-python--21.org.readthedocs.build/en/21/

Integrate with yaml sort.

---

.pre-commit-config.yaml
Makefile
Makefile.jinja
pyproject.toml
pyproject.toml.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--22.org.readthedocs.build/en/22/

Config refine for toml-sort and isort.

---

Makefile

----
:books: Documentation preview :books:: https://serious-scaffold-python--23.org.readthedocs.build/en/23/

Fix typo for make clean in Makefile.

---

.github/workflows/ci.yml
.github/workflows/ci.yml.jinja
README.md.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--34.org.readthedocs.build/en/34/

Check template consistency via Github Actions.

---

Makefile
Makefile.jinja

Fix #29 
----
:books: Documentation preview :books:: https://serious-scaffold-python--35.org.readthedocs.build/en/35/

Check minimal test coverage in make tests.

---

.github/workflows/ci.yml
.github/workflows/ci.yml.jinja
README.md
README.md.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--40.org.readthedocs.build/en/40/

Fix compatibility with copier v8.0.0.

---

.gitlab-ci.yml
.gitlab-ci.yml.jinja
.vscode/settings.json
copier.yaml

----
:books: Documentation preview :books:: https://serious-scaffold-python--39.org.readthedocs.build/en/39/

Add gitlab ci with template.

---

.github/workflows/ci.yml
.github/workflows/ci.yml.jinja
.github/workflows/package.yml
.gitlab-ci.yml
.gitlab-ci.yml.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--45.org.readthedocs.build/en/45/

Show env in CI.

---

README.md
copier.yaml
pyproject.toml
pyproject.toml.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--48.org.readthedocs.build/en/48/

Unify short description.

---

.github/workflows/release.yml
.gitlab-ci.yml
.gitlab-ci.yml.jinja
.readthedocs.yaml
Makefile
Makefile.jinja
copier.yaml
docs/cli/index.rst
docs/cli/index.rst.jinja
docs/index.rst
docs/index.rst.jinja
docs/reports/coverage/index.rst
docs/reports/index.rst
docs/reports/mypy/index.rst
requirements/docs.txt
requirements/lint.txt
src/serious_scaffold/cli.py
src/{{ module_name }}/cli.py.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--72.org.readthedocs.build/en/72/

Add mypy and test coverage reports for docs.

---

.readthedocs.yaml

----
:books: Documentation preview :books:: https://serious-scaffold-python--77.org.readthedocs.build/en/77/

No pdf/epub on readthedocs.

---

.github/workflows/ci.yml
.github/workflows/ci.yml.jinja
src/{{ module_name }}/settings.py.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--87.org.readthedocs.build/en/87/

Better consistency check.

---

.vscode/extensions.json
.vscode/settings.json
Makefile
Makefile.jinja
README.md
README.md.jinja
tests/settings_test.py
tests/settings_test.py.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--90.org.readthedocs.build/en/90/

README refinement with various minor changes.

---

.github/workflows/ci.yml
.github/workflows/ci.yml.jinja
.gitlab-ci.yml
.gitlab-ci.yml.jinja
.pre-commit-config.yaml
.vscode/settings.json
Makefile
Makefile.jinja
README.md
README.md.jinja
pyproject.toml
pyproject.toml.jinja
requirements/test.txt
requirements/tests.txt
test/__init__.py
test/cli_test.py
test/cli_test.py.jinja
test/pkg_test.py
test/pkg_test.py.jinja
test/settings_test.py
test/settings_test.py.jinja
tests/__init__.py

----
:books: Documentation preview :books:: https://serious-scaffold-python--91.org.readthedocs.build/en/91/

Rename tests to test.

---

.pre-commit-config.yaml
Makefile
pyproject.toml
template/.pre-commit-config.yaml
template/Makefile.jinja
template/pyproject.toml.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--100.org.readthedocs.build/en/100/

Refine lint/test configuration.

---

Makefile
template/Makefile.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--102.org.readthedocs.build/en/102/

Refine mypy/coverage reports generation.

---

.github/dependabot.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/dependabot.yml

----
:books: Documentation preview :books:: https://serious-scaffold-python--123.org.readthedocs.build/en/123/

ci: Fix prefix for Dependabot.

---

.github/dependabot.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/dependabot.yml

----
:books: Documentation preview :books:: https://serious-scaffold-python--129.org.readthedocs.build/en/129/

ci(dependabot): Add groups for pip dependabot updates.

---

.vscode/settings.json
docs/api/index.md
docs/api/index.rst
docs/api/settings.md
docs/api/settings.rst
docs/cli/index.md
docs/cli/index.rst
docs/index.md
docs/reports/coverage/index.md
docs/reports/coverage/index.rst
docs/reports/index.md
docs/reports/index.rst
docs/reports/mypy/index.md
docs/reports/mypy/index.rst
template/.vscode/settings.json
template/docs/api/index.md.jinja
template/docs/api/index.rst.jinja
template/docs/api/settings.md.jinja
template/docs/api/settings.rst.jinja
template/docs/cli/index.md.jinja
template/docs/cli/index.rst.jinja
template/docs/index.md.jinja
template/docs/reports/coverage/index.md
template/docs/reports/coverage/index.rst
template/docs/reports/index.md
template/docs/reports/index.rst
template/docs/reports/mypy/index.md
template/docs/reports/mypy/index.rst

----
:books: Documentation preview :books:: https://serious-scaffold-python--134.org.readthedocs.build/en/134/

docs: Use markdown for all documentation.

---

.github/workflows/ci.yml
.gitlab-ci.yml
.vscode/settings.json
Makefile
template/.vscode/settings.json
template/Makefile.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab-ci.yml[% endif %].jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--142.org.readthedocs.build/en/142/

ci: Merge CI pipeline for both GitHub Actions and GitLab CI/CD.

---

Makefile
template/Makefile.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--149.org.readthedocs.build/en/149/

chore: Remove CHANGELOG.md from watch list of docs autobuild.

---

.github/workflows/release.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--162.org.readthedocs.build/en/162/

ci: Fix syntax error for GitHub Actions workflow.

---

.github/workflows/release.yml
Makefile
template/Makefile.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--163.org.readthedocs.build/en/163/

ci: Fix release workflow for GitHub Actions.

---

includes/variable.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--185.org.readthedocs.build/en/185/

fix: fail to replace license_url on gitlab

---

docs/cli/index.md
template/docs/cli/index.md.jinja

----
:books: Documentation preview :books:: https://serious-scaffold-python--205.org.readthedocs.build/en/205/

docs: Fix rst parsing in cli reference.

---

.vscode/extensions.json
docs/conf.py
docs/dev/env.md
template/.vscode/extensions.json
template/docs/conf.py.jinja
template/docs/dev/env.md

----
:books: Documentation preview :books:: https://serious-scaffold-python--213.org.readthedocs.build/en/213/

docs: No code fence and the official myst VSCode extension.

---

.github/workflows/release.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja

After merging this pull request, we should remove the settings for `TWINE_USERNAME` and release a new version for test.
----
:books: Documentation preview :books:: https://serious-scaffold-python--232.org.readthedocs.build/en/232/

ci(github): Set default value for TWINE_USERNAME env to '__token__'.

---

.pre-commit-config.yaml
template/.pre-commit-config.yaml.jinja

`pdm lock` and `pdm lock --check` are almost not the same thing. `pdm lock --check` will just check against the lock file and `pdm lock` will resolve the dependencies again and lead to potential update.
----
📚 Documentation preview 📚: https://ss-python--268.org.readthedocs.build/en/268/

chore: Use check for pdm lock.

---

.pre-commit-config.yaml
template/.pre-commit-config.yaml.jinja

For Json/Jsonc lint/formatter/pre-commit, another issue is created to track.
----
📚 Documentation preview 📚: https://ss-python--278.org.readthedocs.build/en/278/

chore: Remove json related pre-commit hooks due to jsonc incompatibility.

---

.devcontainer/prebuild/.devcontainer/Dockerfile
template/.devcontainer/prebuild/.devcontainer/Dockerfile.jinja

…ainer.
----
📚 Documentation preview 📚: https://ss-python--285.org.readthedocs.build/en/285/

chore: Use bash as the default shell for the non-root user in devcontainer.

---

.github/workflows/devcontainer.yml
.gitlab/workflows/devcontainer.yml
.gitlab/workflows/release.yml
README.md
includes/variable.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/devcontainer.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/devcontainer.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/release.yml.jinja

1. GitLab Pages need to explicitly dependon on `pages-build` so as to use the artifacts.
2. DevContainer workflow is needed for bootstrap which will be triggerred manually.
Sorry for the regression due to previous changes.
----
📚 Documentation preview 📚: https://ss-python--298.org.readthedocs.build/en/298/

ci: Fix GitLab Pages deploy, revert devconatiner workflow for bootstrap.

---

Makefile
template/Makefile.jinja

In CI/CD, we will use `make release-notes > release-notes.md` to generate the release notes. Previously, the command `git-changelog --input docs/changelog.md --release-notes` will be included.
----
📚 Documentation preview 📚: https://ss-python--300.org.readthedocs.build/en/300/

doc: Remove command from generated release notes.

---

.gitlab/workflows/devcontainer.yml
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/devcontainer.yml.jinja

----
📚 Documentation preview 📚: https://ss-python--302.org.readthedocs.build/en/302/

ci: Remove redundant tag for dev container built on default branch.

---

.github/workflows/release.yml
Makefile
template/Makefile.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja

Previously, changelog and release-notes are generated in separate jobs. This makes the whole process much complicated with extra steps to fetch the repo, delete files to be overridden, install `git-changelog` separately. We even have to hack Makefile so as to use `git-changelog` without `pdm` installed. Actaully, the release notes can be generated in `pages-build` job and only release notes need to be uploaded to publish a release as artifacts. Moreover, this makes it consistent with what we do in GitLab CI/CD.
----
📚 Documentation preview 📚: https://ss-python--303.org.readthedocs.build/en/303/

ci: Refine release notes generation.

---

.devcontainer/devcontainer.json
.github/workflows/devcontainer.yml
.github/workflows/release.yml
.gitlab-ci.yml
.gitlab/workflows/ci.yml
.gitlab/workflows/devcontainer.yml
.gitlab/workflows/release.yml
docs/dev/proj.md
docs/dev/release.md
template/.devcontainer/devcontainer.json.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/devcontainer.yml.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab-ci.yml[% endif %].jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/devcontainer.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/release.yml.jinja
template/docs/dev/proj.md.jinja
template/docs/dev/release.md.jinja

Previously, we use a single repository and differentiated containers solely based on tags. Taking project versions into consideration has made this approach more complicated. Here we unify the containers naming pattern into three categories:
- `ghcr.io/serious-scaffold/ss-python:py3.12` for production image.
- `ghcr.io/serious-scaffold/ss-python/dev:py3.12` for development image.
- `ghcr.io/serious-scaffold/ss-python/dev-cache:py3.12` for build cache of development image.
In the furture, when we have build cache of production image, we can still leverage the similar pattern.
----
📚 Documentation preview 📚: https://ss-python--309.org.readthedocs.build/en/309/

chore: unify naming pattern for containers

---

.github/workflows/ci.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja

This fixes ci workflow on the main branch in forked repo.
Reference: https://github.com/huxuan/ss-python/actions/workflows/ci.yml
----
📚 Documentation preview 📚: https://ss-python--311.org.readthedocs.build/en/311/

ci: dynamic CI_PAGES_URL env for ci workflow on GitHub

---

.github/workflows/renovate.yml
.gitlab/workflows/ci.yml
.gitlab/workflows/commitlint.yml
.gitlab/workflows/devcontainer.yml
.gitlab/workflows/renovate.yml
.renovaterc.json
.vscode/settings.json
template/.renovaterc.json
template/.renovaterc.json.jinja
template/.vscode/settings.json
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/renovate.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/commitlint.yml
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/devcontainer.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/renovate.yml

An expected result can be found here: 
- https://github.com/huxuan/ss-python/issues/5
- https://gitlab.com/huxuan8528/ss-python/-/issues/1
Note that only `pep621` (for GitHub and GitLab) and `github-actions` (for GitHub only) managers are enabled as others needs further configuration. 
----
📚 Documentation preview 📚: https://ss-python--321.org.readthedocs.build/en/321/

chore: add initial version of renovate config

---

.github/workflows/renovate.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/renovate.yml.jinja

Expected workflow run: 
- PAT directly as RENOVATE_TOKEN: https://github.com/huxuan/ss-python/actions/runs/8014762535/job/21893880462 
- Generate token with GitHub App: <del>https://github.com/huxuan/ss-python/actions/runs/8014581681/job/21893417864</del>https://github.com/huxuan/ss-python/actions/runs/8014602038/job/21893474172
Expected pull requests when using GitHub App:
- https://github.com/huxuan/ss-python/pull/6
- https://github.com/huxuan/ss-python/pull/7
----
📚 Documentation preview 📚: https://ss-python--327.org.readthedocs.build/en/327/

chore: authenticate renovate with github app when configured

---

.github/workflows/renovate.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/renovate.yml.jinja

The [default schedule](https://docs.renovatebot.com/configuration-options/#lockfilemaintenance) for [maintainlockfilesweekly](https://docs.renovatebot.com/presets-default/#maintainlockfilesweekly) is `before 4am on monday` which looks to be a good convention to follow.

chore: sync renovate cron with preset 'maintainLockFilesWeekly'

---

docs/conf.py
template/docs/conf.py.jinja

----
📚 Documentation preview 📚: https://ss-python--341.org.readthedocs.build/en/341/

docs: avoid line too long problem when the project name is long

---

.github/workflows/renovate.yml
.gitlab/workflows/renovate.yml
.renovaterc.json
template/.renovaterc.json.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/renovate.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/renovate.yml

With this pull request, we should generate the `.renovaterc.json` for end users which only update those generated files.
----
📚 Documentation preview 📚: https://ss-python--340.org.readthedocs.build/en/340/

chore: config gitlabci manager for renovate

---

.copier-data.yml
.github/workflows/ci.yml
Makefile
copier.yaml
template/Makefile.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja

Previously, data file specific to serious-scaffold-python and template default value are mixed. Now we would like to separate them so that we can easily manage a demo project or test with different values in the future.
----
📚 Documentation preview 📚: https://ss-python--359.org.readthedocs.build/en/359/

chore: separate specific data file and default value

---

docs/dev/proj.md
template/docs/dev/proj.md.jinja

Please refer to the corresponding section here: https://ss-python--364.org.readthedocs.build/en/364/dev/proj.html#project-configuration
Note that there are two tabs for GitHub and GitLab respectively.
----
📚 Documentation preview 📚: https://ss-python--364.org.readthedocs.build/en/364/

docs: update project configuration with renovate authentication

---

.renovaterc.json
template/.renovaterc.json.jinja

Reduce the number of pull requests for maintenance
Expected result: https://github.com/huxuan/ss-python/pull/27
----
📚 Documentation preview 📚: https://ss-python--375.org.readthedocs.build/en/375/

chore: group renovate docker tags for serious-scaffold-python only

---

.devcontainer/Dockerfile
.renovaterc.json
template/.devcontainer/Dockerfile.jinja
template/.renovaterc.json.jinja

----
📚 Documentation preview 📚: https://ss-python--368.org.readthedocs.build/en/368/

chore: fix Python 3.8 compatibility issue

---

.gitlab/workflows/commitlint.yml
.gitlab/workflows/release.yml
.gitlab/workflows/renovate.yml
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/commitlint.yml
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/release.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/renovate.yml

----
📚 Documentation preview 📚: https://ss-python--374.org.readthedocs.build/en/374/

chore: set GIT_STRATEGY to none for jobs need no repo code in GitLab CI/CD

---

.github/workflows/readthedocs-preview.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/readthedocs-preview.yml.jinja

Test:
- https://github.com/huxuan/ss-python/pull/30
- https://github.com/huxuan/ss-python/pull/31
- https://github.com/huxuan/ss-python/pull/32
Actually, I am a little confused about the preview link in this pull request. Seems the changes to workflows does not take effect immediately. Let me know if I made anything wrong.
----
📚 Documentation preview 📚: https://ss-python--377.org.readthedocs.build/en/377/

chore: trigger readthedocs preview only when docs change

---

.github/workflows/renovate.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/renovate.yml.jinja

Unlike GitLab CI/CD, containerized GitHub Action jobs need to specify the mapping of environment variables.
Ref: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container#using-environment-variables-with-a-container
----
📚 Documentation preview 📚: https://ss-python--387.org.readthedocs.build/en/387/

chore: support RENOVATE_ENABLED in GitHub Actions

---

.gitlab/workflows/commitlint.yml
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/commitlint.yml

Commitlint needs configuration to run, which is included in the source code.
https://gitlab.com/huxuan8528/ss-python/-/jobs/6360858768
Sorry for the introduced bug. :-(

chore: fix commitlint GIT_STRATEGY in GitLab CI/CD

---

.renovaterc.json
template/.renovaterc.json.jinja

Sorry for the typo that leads to the following inconsistency error.
Failed pull request: https://github.com/serious-scaffold/ss-python/pull/395
Failed workflow: https://github.com/serious-scaffold/ss-python/actions/runs/8273933284/job/22638514452?pr=395
Fixed pull request: https://github.com/huxuan/ss-python/pull/58
Fixed workflow: https://github.com/huxuan/ss-python/actions/runs/8274060306/job/22638839560?pr=58

chore: fix typo in matchDepTypes in renovate configuration

---

.github/workflows/ci.yml
.github/workflows/devcontainer.yml
.github/workflows/release.yml
.github/workflows/renovate.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/ci.yml.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/devcontainer.yml.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/renovate.yml.jinja

According to the [GitHub Actions VSCode Extension](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions).

chore: unify quotation marks in GitHub Action Workflows

---

.github/workflows/readthedocs-preview.yml
.readthedocs.yaml
template/.readthedocs.yaml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/readthedocs-preview.yml.jinja

According to the discussion here: https://github.com/readthedocs/actions/issues/39, we prefer to disable the preview documentation build when there is no relevant changes.
Test pull requests:
- no doc related changes: https://github.com/serious-scaffold/ss-python/pull/410
- doc related changes: https://github.com/serious-scaffold/ss-python/pull/411
----
📚 Documentation preview 📚: https://ss-python--406.org.readthedocs.build/en/406/

chore: cancel build on Read the Docs conditionally

---

.github/workflows/renovate.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/renovate.yml.jinja

For GitLab, it works natively. Please refer to: https://gitlab.com/huxuan8528/ss-python/-/merge_requests/35/commits. But it is a pity that the random string of the email address on GitLab for bot users is a must have pattern when compared with GitHub.

chore: inject RENOVATE_GIT_AUTHOR vars in GitHub Actions

---

.renovaterc.json
template/.renovaterc.json.jinja

Expected results: https://github.com/huxuan/ss-python/pull/74

chore: group renovate docker tag and pre-commit-hooks tag

---

.renovaterc.json
template/.renovaterc.json.jinja

Expected workflow: https://github.com/huxuan/ss-python/actions/runs/8466026206/job/23194021191
Expected pull request: https://github.com/huxuan/ss-python/pull/83 (The CI is failed as expected)

chore: update pdm in setup-pdm action with renovate

---

.github/workflows/release.yml
.gitlab/workflows/release.yml
.readthedocs.yaml
.renovaterc.json
Makefile
pyproject.toml
template/.readthedocs.yaml
template/.readthedocs.yaml.jinja
template/.renovaterc.json.jinja
template/Makefile.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/release.yml.jinja
template/pyproject.toml.jinja

1. Avoid unnecessary no editable installtion since upstream change: https://github.com/pdm-project/pdm-backend/commit/e6fcd5fcc2abae9ab25a9d69c71fd066de184110
2. Refine `.readthdocs.yaml` mostly refer to https://github.com/pdm-project/pdm/blob/main/.readthedocs.yaml
1. Set `VIRTUAL_ENV` as a trick, ref: https://github.com/pdm-project/pdm/issues/2856#issuecomment-2081301478
2. Install pdm with asdf
3. Update pdm installed with asdf with renovate
4. pin `pdm-backend` and update with renovate including template

refactor: enhance pdm and Read the Docs integration

---

.github/workflows/devcontainer.yml
.github/workflows/release.yml
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/devcontainer.yml.jinja
template/[% if repo_host_type == 'github.com' %].github[% endif %]/workflows/release.yml.jinja

Previously, we leverage bunch of existing GitHub Actions for docker related operations on GitHub while raw commands on GitLab, this brings extra efforts for maintanence.
It should work as expected, even for the cache:
- DevContainer workflow: https://github.com/huxuan/ss-python/actions/runs/8978552222
- Release workflow: https://github.com/huxuan/ss-python/actions/runs/8978566687

ci: unify docker behavior

---

.gitlab/workflows/ci.yml
.gitlab/workflows/release.yml
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja
template/[% if repo_host_type == 'gitlab.com' or repo_host_type == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/release.yml.jinja

Fix #174 
Test jobs:
- Before: https://gitlab.com/huxuan8528/ss-python/-/jobs/6794186310
- After: https://gitlab.com/huxuan8528/ss-python/-/jobs/6794212803
It saves about 20 seconds, from 1m38s to 1m10s.

ci: enable cache in GitLab CI/CD

---

README.md
includes/sample.jinja

Fix #491 
----
📚 Documentation preview 📚: https://ss-python--530.org.readthedocs.build/en/530/

docs: emphasize multiple Python versions in Features

---

README.md
includes/sample.jinja

This is more for proposal and discussion, any suggestions are welcome.
----
📚 Documentation preview 📚: https://ss-python--535.org.readthedocs.build/en/535/

chore: update Features in README

---

README.md
includes/sample.jinja

Fix #536 
----
📚 Documentation preview 📚: https://ss-python--537.org.readthedocs.build/en/537/

docs: remove badge section in README

---

.github/workflows/renovate.yml
docs/management/config.md
template/[% if repo_platform == 'github' %].github[% endif %]/workflows/renovate.yml.jinja
template/docs/management/config.md.jinja

----
📚 Documentation preview 📚: https://ss-python--557.org.readthedocs.build/en/557/

ci: unify secrets in GitHub Actions

---

.gitlab/workflows/ci.yml
.gitlab/workflows/release.yml
package.json
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/release.yml.jinja
template/package.json.jinja

1. pipeline for semantic-release: https://gitlab.com/huxuan8528/ss-python/-/pipelines/1294606691
2. pipeline for release after semantic-release: https://gitlab.com/huxuan8528/ss-python/-/pipelines/1294637957
3. New release: https://gitlab.com/huxuan8528/ss-python/-/releases/v0.0.51
BTW, documentation are not included in this pull request and it was noted as subtasks in #549

ci: integrate semantic release in GitLab CI/CD

---

.gitlab/workflows/ci.yml
.gitlab/workflows/renovate.yml
docs/management/config.md
package.json
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/renovate.yml
template/docs/management/config.md.jinja

----
📚 Documentation preview 📚: https://ss-python--559.org.readthedocs.build/en/559/

ci: unify PAT as token in GitLab CI/CD

---

.github/workflows/commitlint.yml
template/[% if repo_platform == 'github' %].github[% endif %]/workflows/commitlint.yml

I suppose to use `npx` to run `commitlint` directly but it turns out there is still an open issue from 2019 (https://github.com/conventional-changelog/commitlint/issues/613), so finally I give up and decide to use container image instead.

ci: use container image for commitlint on GitHub Actions

---

.gitlab/workflows/ci.yml
.gitlab/workflows/renovate.yml
package.json
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/renovate.yml

The varialbe check on GitLab CI/CD is quite strange:
When assign `$PAT` to `$GITLAB_TOKEN` and `$PAT` is NEVER configured:
1. `$GITLAB_TOKEN != null`: the [job](https://gitlab.com/huxuan8528/ss-python/-/pipelines/1296849230) will be triggered. 
2. `$GITALB_TOKEN != ""`: the [job](https://gitlab.com/huxuan8528/ss-python/-/pipelines/1296848929) will be triggered.
3. `$PAT != null`, the [job](https://gitlab.com/huxuan8528/ss-python/-/pipelines/1296849378) will NOT be triggered. 
4. `$PAT != ""`, the [job](https://gitlab.com/huxuan8528/ss-python/-/pipelines/1296848448) will be triggered.
In conclusion, we have to `$PAT != null` to avoid unexpected job run.
Some related reference:
- https://gitlab.com/gitlab-org/gitlab/-/issues/206960
- https://gitlab.com/gitlab-org/gitlab/-/issues/220562

ci: fix variable null chek on GitLab CI/CD

---

.github/workflows/renovate.yml
.gitlab/workflows/renovate.yml
.pre-commit-config.yaml
.renovaterc.json
docs/management/update.md
template/.pre-commit-config.yaml.jinja
template/.renovaterc.json.jinja
template/[% if repo_platform == 'github' %].github[% endif %]/workflows/renovate.yml.jinja
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/renovate.yml
template/docs/management/update.md

1. Use slim version of renovate container image
2. Constraints python and pdm version in Renovate.
3. Manage the pdm version in the renovate constraints by renovate.
4. Unify pdm version specified in `pdm-project/setup-pdm` GitHub Actions.
5. Update related documentation.
- GitHub Actions: https://github.com/huxuan/ss-python/actions/runs/9203981154/job/25316623373
- Search keyword "install-tool" and "constraints" to see how it takes effect
- Pull request:
- https://github.com/huxuan/ss-python/pull/108
- https://github.com/huxuan/ss-python/pull/111   
With slim renovate docker image, it should saves time for container initialization. With fixed version of Python and pdm, it should bring more reproducibility.

chore: use slim renovate with constraints

---

.devcontainer/Dockerfile
.github/workflows/release.yml
.gitlab/workflows/release.yml
README.md
includes/sample.jinja
pyproject.toml
template/.devcontainer/Dockerfile.jinja
template/[% if repo_platform == 'github' %].github[% endif %]/workflows/release.yml.jinja
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/release.yml.jinja
template/pyproject.toml.jinja

Prefer setuptools since it supports C extension natively. I just realize that `pdm-backend` supports C extension by leverage `setuptools`. :-(
Test workflow:
- Semantic Release: https://github.com/huxuan/ss-python/actions/runs/9205816111/job/25322316985
- Package Publish (failed for publish authentication): https://github.com/huxuan/ss-python/actions/runs/9205821904/job/25322336090
- Container Publish (one of them): https://github.com/huxuan/ss-python/actions/runs/9205821904/job/25322337453 
----
📚 Documentation preview 📚: https://ss-python--580.org.readthedocs.build/en/580/

build: replace pdm-backends with setuptools and setuptools-scm

---

README.md
docs/development/index.md
docs/development/tests.md
includes/sample.jinja
template/docs/development/index.md
template/docs/development/tests.md.jinja

----
📚 Documentation preview 📚: https://ss-python--610.org.readthedocs.build/en/610/

docs: add documentation for tests

---

.readthedocs.yaml
.renovaterc.json
docs/management/update.md
template/.readthedocs.yaml.jinja
template/.renovaterc.json.jinja
template/docs/management/update.md

----
📚 Documentation preview 📚: https://ss-python--622.org.readthedocs.build/en/622/

chore: use pipx instead of asdf for readthedocs

---

docs/management/init.md
template/docs/management/init.md.jinja

----
📚 Documentation preview 📚: https://ss-python--629.org.readthedocs.build/en/629/

docs: fix git clone url

---

.pre-commit-config.yaml
Makefile
README.md
includes/sample.jinja
pdm.lock
pyproject.toml
template/.pre-commit-config.yaml.jinja
template/Makefile.jinja
template/pyproject.toml.jinja

----
📚 Documentation preview 📚: https://ss-python--635.org.readthedocs.build/en/635/

refactor: replace toml-sort with pyproject-fmt

---

.devcontainer/Dockerfile
.renovaterc.json
Makefile
README.md
docs/development/setup-dev-env.md
docs/management/init.md
includes/sample.jinja
template/.devcontainer/Dockerfile.jinja
template/.renovaterc.json.jinja
template/Makefile.jinja
template/docs/development/setup-dev-env.md
template/docs/management/init.md.jinja

----
📚 Documentation preview 📚: https://ss-python--637.org.readthedocs.build/en/637/

refactor: manage pdm and pre-commit with make prerequisites

---

.pre-commit-config.yaml
.vscode/settings.json
Makefile
pyproject.toml
template/.pre-commit-config.yaml.jinja
template/.vscode/settings.json
template/Makefile.jinja
template/pyproject.toml.jinja

----
📚 Documentation preview 📚: https://ss-python--638.org.readthedocs.build/en/638/

chore: integrate codespell

---

.readthedocs.yaml
Makefile
pyproject.toml
template/.readthedocs.yaml.jinja
template/Makefile.jinja
template/pyproject.toml.jinja

1. Use `pdm sync` instead of `pdm install` for speed up: https://pdm-project.org/latest/usage/lockfile/#install-the-packages-pinned-in-lock-file
2. Avoid run `mypy` twice in CI.
3. Slightly unify name `doc-build` v.s. `doc-autobuild`.
----
📚 Documentation preview 📚: https://ss-python--639.org.readthedocs.build/en/639/

refactor: refine Makefile

---

docs/development/commit.md
docs/development/setup-dev-env.md
docs/management/release.md
template/docs/development/commit.md
template/docs/development/setup-dev-env.md
template/docs/management/release.md.jinja

----
📚 Documentation preview 📚: https://ss-python--649.org.readthedocs.build/en/649/

docs: use absolute url in docs

---

.renovaterc.json
template/.renovaterc.json.jinja

Run log: https://github.com/huxuan/ss-python/actions/runs/9856250054/job/27212842078
New parsed result: (Captured from https://github.com/huxuan/ss-python/issues/63)
T current parsed result: (Captured from https://github.com/serious-scaffold/ss-python/issues/331)

fix: fix renovate regex match for pip/pipx

---

.readthedocs.yaml
.renovaterc.json
template/.readthedocs.yaml.jinja
template/.renovaterc.json.jinja

This should fix the CI/CD error in https://github.com/serious-scaffold/ss-python/pull/748
----
📚 Documentation preview 📚: https://ss-python--757.org.readthedocs.build/en/757/

fix: fix renovate for github runner update

---

.github/workflows/ci.yml
.github/workflows/devcontainer.yml
.github/workflows/release.yml
.gitlab/workflows/ci.yml
.gitlab/workflows/devcontainer.yml
.gitlab/workflows/release.yml
.renovaterc.json
Makefile
copier.yaml
includes/copier-answers-sample.yml
pdm.lock
pyproject.toml
template/.renovaterc.json.jinja
template/Makefile.jinja
template/[% if repo_platform == 'github' %].github[% endif %]/workflows/ci.yml.jinja
template/[% if repo_platform == 'github' %].github[% endif %]/workflows/devcontainer.yml.jinja
template/[% if repo_platform == 'github' %].github[% endif %]/workflows/release.yml.jinja
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/devcontainer.yml.jinja
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/release.yml.jinja
template/pyproject.toml.jinja

Reference: https://devguide.python.org/versions/
----
📚 Documentation preview 📚: https://ss-python--758.org.readthedocs.build/en/758/

feat(no-release): drop support of 3.8 and add support of 3.13

---

.gitlab/workflows/ci.yml
.pre-commit-config.yaml
.renovaterc.json
Makefile
template/.pre-commit-config.yaml.jinja
template/.renovaterc.json.jinja
template/Makefile.jinja
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/ci.yml.jinja

----
📚 Documentation preview 📚: https://ss-python--782.org.readthedocs.build/en/782/

feat(no-release): add check-jsonchema for lint

---

docs/advanced/cicd.md
docs/advanced/index.md
template/docs/advanced/cicd.md.jinja
template/docs/advanced/index.md

Fix #611
----
📚 Documentation preview 📚: https://ss-python--795.org.readthedocs.build/en/795/

docs: add docs for CI/CD

---

Makefile
template/Makefile.jinja

question:
test result:
make template-build && git diff:
----
📚 Documentation preview 📚: https://ss-python--805.org.readthedocs.build/en/805/

fix: make dev failed when lockfile does not exist

---

.github/workflows/renovate.yml
.gitlab/workflows/renovate.yml
template/[% if repo_platform == 'github' %].github[% endif %]/workflows/renovate.yml.jinja
template/[% if repo_platform == 'gitlab' or repo_platform == 'gitlab-self-managed' %].gitlab[% endif %]/workflows/renovate.yml

Fix error happens when renovate trying to update development lock file in #824
A successful result can be found in https://github.com/huxuan/ss-python/pull/117

fix: pdm update bug in renovate

---

README.md
includes/sample.jinja

----
📚 Documentation preview 📚: https://ss-python--877.org.readthedocs.build/en/877/

docs: add more features in README

---

pdm.dev.lock
pdm.lock
pyproject.toml
template/pyproject.toml.jinja

----
📚 Documentation preview 📚: https://ss-python--884.org.readthedocs.build/en/884/

feat(no-release): use dependency-groups according to pep735

---

.renovaterc.json
Makefile
template/.renovaterc.json.jinja
template/Makefile.jinja

----
📚 Documentation preview 📚: https://ss-python--887.org.readthedocs.build/en/887/

refactor: refine make prerequisites

---

.releaserc.json
docs/management/release.md
template/.releaserc.json.jinja
template/docs/management/release.md.jinja

----
📚 Documentation preview 📚: https://ss-python--890.org.readthedocs.build/en/890/

chore(patch-release): add more release scope for semantic-release

---

Makefile
pdm.dev.lock
pdm.lock
pyproject.toml
src/ss_python/cli.py
template/Makefile.jinja
template/pyproject.toml.jinja
template/src/{{ module_name }}/cli.py.jinja

----
📚 Documentation preview 📚: https://ss-python--896.org.readthedocs.build/en/896/

chore(patch-release): misc refinements

---

docs/cli/index.md
docs/cli/run.md
docs/cli/ss_python.md
template/docs/cli/index.md.jinja
template/docs/cli/run.md.jinja
template/docs/cli/{{ module_name }}.md.jinja

----
📚 Documentation preview 📚: https://ss-python--898.org.readthedocs.build/en/898/

docs: split cli reference for each sub command

---

.renovaterc.json
template/.renovaterc.json.jinja

PR example:
- https://github.com/huxuan/ss-python/pull/122

fix: update readthedocs/action/preview GitHub Action in template

---

.github/workflows/ci.yml
.github/workflows/commitlint.yml
.github/workflows/readthedocs-preview.yml
.github/workflows/release.yml
.github/workflows/renovate.yml
template/{% if repo_platform == 'github' %}.github{% endif %}/workflows/ci.yml.jinja
template/{% if repo_platform == 'github' %}.github{% endif %}/workflows/commitlint.yml
template/{% if repo_platform == 'github' %}.github{% endif %}/workflows/readthedocs-preview.yml.jinja
template/{% if repo_platform == 'github' %}.github{% endif %}/workflows/release.yml.jinja
template/{% if repo_platform == 'github' %}.github{% endif %}/workflows/renovate.yml.jinja

----
📚 Documentation preview 📚: https://ss-python--979.org.readthedocs.build/en/979/

chore: format github workflows
